name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - run: npm ci
      - name: build
#        TODO Enable those lines below if you use a Redis cache, you'll also need to configure GitHub Repository Secrets
#        env:
#          REDIS_HOST: ${{ secrets.REDIS_HOST }}
#          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
        run: npm run build
